# -*- coding: utf-8 -*-
"""teleAlert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr8InpYeMZPNzZSn7QxCY-Bsz_qGdhQs
"""

pip install telepot

from keras.models import load_model
from collections import deque
import matplotlib.pyplot as plt
import numpy as np
import argparse
import pickle
import cv2
import telepot
from datetime import datetime
import pytz

def getTime():
  IST = pytz.timezone('Asia/Kolkata')
  timeNow = datetime.now(IST)
  return timeNow

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense
from tensorflow.keras.models import Model

IMG_SIZE = 128

def build_model():
    base_model = MobileNetV2(
        weights="imagenet",
        include_top=False,
        input_shape=(IMG_SIZE, IMG_SIZE, 3)
    )

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    outputs = Dense(1, activation="sigmoid")(x)

    model = Model(inputs=base_model.input, outputs=outputs)

    return model

import cv2
import numpy as np
import time
import telepot
from collections import deque
from google.colab.patches import cv2_imshow


def print_results(video, limit=None):

    trueCount = 0
    imageSaved = 0
    filename = "savedImage.jpg"
    sendAlert = 0
    location = "Bangalore"

    print("Loading model architecture + weights ...")

    # 🔥 build architecture
    model = build_model()

    # 🔥 load trained weights
    model.load_weights("/content/drive/MyDrive/modelnew.weights.h5")

    # 🔔 Telegram setup (PUT YOUR VALUES)
    BOT_TOKEN = "8316492484:AAERVCVocGf4WZVPh1yNDstaZafG6gxiL-w"
    CHAT_ID = "-1003519540779"
    bot = telepot.Bot(BOT_TOKEN)

    Q = deque(maxlen=128)
    vs = cv2.VideoCapture(video)
    writer = None
    (W, H) = (None, None)

    while True:
        grabbed, frame = vs.read()
        if not grabbed:
            break

        if W is None or H is None:
            (H, W) = frame.shape[:2]

        output = frame.copy()

        # preprocessing
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE)).astype("float32") / 255.0

        preds = model.predict(np.expand_dims(frame, axis=0), verbose=0)[0]
        Q.append(preds)

        avg_pred = np.mean(Q)
        label = avg_pred > 0.5

        text_color = (0, 0, 255) if label else (0, 255, 0)

        if label:
            trueCount += 1

        text = f"Violence: {label} ({avg_pred:.2f})"
        cv2.putText(output, text, (35, 50),
                    cv2.FONT_HERSHEY_SIMPLEX, 1.25, text_color, 3)

        # video writer
        if writer is None:
            fourcc = cv2.VideoWriter_fourcc(*"MJPG")
            writer = cv2.VideoWriter("recordedVideo.avi", fourcc, 30, (W, H), True)

        writer.write(output)
        cv2_imshow(output)

        # 🚨 TELEGRAM ALERT LOGIC
        if trueCount >= 50 and sendAlert == 0:

            # save evidence image
            if imageSaved == 0:
                cv2.imwrite(filename, output)
                imageSaved = 1

            # send telegram alert
            current_time = time.strftime("%Y-%m-%d %H:%M:%S")

            bot.sendMessage(
                CHAT_ID,
                f"🚨 VIOLENCE ALERT!\nLocation: {location}\nTime: {current_time}"
            )

            bot.sendPhoto(CHAT_ID, photo=open(filename, "rb"))

            print("✅ Telegram alert sent")
            sendAlert = 1

        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
            break

    print("[INFO] cleaning up...")
    if writer:
        writer.release()
    vs.release()

V_path = "/content/drive/MyDrive/dataset/Real Life Violence Dataset/Violence/V_103.mp4"

print_results(V_path)